### ISSUE TITLE
Add hour markers to the historical graph?

### ISSUE THREAD

**Issue by katrinabarlow** [thomaswilburn/powerhouse-demo#2]

**Comment by thomaswilburn** [comment]
Hours or days, sure. We definitely do need some sort of legitimizing labels on it, so it doesn't seem so random.

**Comment by katrinabarlow** [comment]
:+1:

**Comment by thomaswilburn** [comment]
This is closed as of a couple of days ago. The labels are set in the historical.less file, and currently divide it into quarters as if it was a 24-hour period.
