### ISSUE TITLE
Add labels to the bar graph (e.g., coal, natural gas)

### ISSUE THREAD

**Issue by katrinabarlow** [thomaswilburn/powerhouse-demo#3]

**Comment by katrinabarlow** [comment]
One issue that might crop up is if labels won't fit in a stacked bar. One solution might be to go to individual bars, where the largest % fuel would be 100% and the rest would scale based on the primary fuel? Or labels on touch/hover?

**Comment by thomaswilburn** [comment]
My plan was to put all labels in a pop-over that appears when you touch/hover the graph, similar to the way this tax levy chart that Audrey did works: http://projects.seattletimes.com/2015/politics/tax-levies/

**Comment by katrinabarlow** [comment]
I LIKE IT!
