### ISSUE TITLE
Add color indicator to carbon score?

### ISSUE THREAD

**Issue by katrinabarlow** [thomaswilburn/powerhouse-demo#5]
What do you think about adding a class to the carbon score, so that it is green when it's lower than your preset carbon limit, yellow when it's within 5 points of your limit, and red anytime that it's above?

**Comment by thomaswilburn** [comment]
Sure, I can do that. I'll set it up and then you can tweak the colors.

**Comment by katrinabarlow** [comment]
It's looking so good, Thomas!
